version: "3.8"

services:
  backend:
    build: .
    image: hms_backend_alt
    container_name: hms_backend_alt_container
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_lE5P7uVCzLMf@ep-super-frog-a19xt3it-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=change_this_to_a_secure_secret_in_production_at_least_32_chars
      - COOKIE_SECURE=False
    restart: always
