-- Seed Permissions
INSERT INTO permissions (id, permission_key, description, created_at) VALUES
(gen_random_uuid(), 'platform:tenants:read', 'View tenant (hotel) list and details', NOW()),
(gen_random_uuid(), 'platform:tenants:write', 'Create and update tenants', NOW()),
(gen_random_uuid(), 'platform:tenants:delete', 'Delete tenants', NOW()),
(gen_random_uuid(), 'platform:plans:read', 'View subscription plans', NOW()),
(gen_random_uuid(), 'platform:plans:write', 'Manage subscription plans', NOW()),
(gen_random_uuid(), 'platform:users:read', 'View platform users', NOW()),
(gen_random_uuid(), 'platform:users:write', 'Manage platform users', NOW()),
(gen_random_uuid(), 'platform:roles:read', 'View system roles', NOW()),
(gen_random_uuid(), 'platform:roles:write', 'Manage system roles and permissions', NOW()),
(gen_random_uuid(), 'platform:kiosks:read', 'View kiosk fleet', NOW()),
(gen_random_uuid(), 'platform:kiosks:write', 'Manage kiosk hardware and firmware', NOW()),
(gen_random_uuid(), 'platform:billing:read', 'View platform billing and invoices', NOW()),
(gen_random_uuid(), 'platform:billing:write', 'Manage billing and payments', NOW()),
(gen_random_uuid(), 'platform:reports:read', 'Access platform-wide reports', NOW()),
(gen_random_uuid(), 'hotel:users:read', 'View hotel staff list', NOW()),
(gen_random_uuid(), 'hotel:users:write', 'Manage hotel staff', NOW()),
(gen_random_uuid(), 'hotel:roles:read', 'View hotel-specific roles', NOW()),
(gen_random_uuid(), 'hotel:roles:write', 'Manage hotel roles and permissions', NOW()),
(gen_random_uuid(), 'hotel:rooms:read', 'View room status and inventory', NOW()),
(gen_random_uuid(), 'hotel:rooms:write', 'Manage rooms and categories', NOW()),
(gen_random_uuid(), 'hotel:bookings:read', 'View guest bookings', NOW()),
(gen_random_uuid(), 'hotel:bookings:write', 'Create and manage bookings', NOW()),
(gen_random_uuid(), 'hotel:housekeeping:read', 'View cleaning tasks', NOW()),
(gen_random_uuid(), 'hotel:housekeeping:write', 'Manage housekeeping assignments', NOW()),
(gen_random_uuid(), 'hotel:incidents:read', 'View maintenance incidents', NOW()),
(gen_random_uuid(), 'hotel:incidents:write', 'Report and resolve incidents', NOW()),
(gen_random_uuid(), 'hotel:invoices:read', 'View hotel invoices', NOW()),
(gen_random_uuid(), 'hotel:invoices:write', 'Generate and manage invoices', NOW()),
(gen_random_uuid(), 'hotel:reports:read', 'Access hotel-level analytics', NOW()),
(gen_random_uuid(), 'platform:*:*', 'Full Platform Access', NOW()),
(gen_random_uuid(), 'hotel:*:*', 'Full Hotel Access', NOW())
ON CONFLICT (permission_key) DO NOTHING;
