"""Add status to tenants and tenant_users

Revision ID: 0cd91be3c5f3
Revises: a56ed45b6a79
Create Date: 2026-03-04 06:06:47.408842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cd91be3c5f3"
down_revision: Union[str, Sequence[str], None] = "a56ed45b6a79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_users",
        sa.Column("status", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.add_column(
        "tenants",
        sa.Column("status", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "status")
    op.drop_column("tenant_users", "status")
    # ### end Alembic commands ###
