"""add_readable_id_to_users

Revision ID: 17a08d47a3f5
Revises: 454e6b31d7cb
Create Date: 2026-03-04 07:59:02.240199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a08d47a3f5'
down_revision: Union[str, Sequence[str], None] = '454e6b31d7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_users', sa.Column('readable_id', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'platform_users', ['readable_id'])
    op.add_column('tenant_users', sa.Column('readable_id', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'tenant_users', ['readable_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_users', type_='unique')
    op.drop_column('tenant_users', 'readable_id')
    op.drop_constraint(None, 'platform_users', type_='unique')
    op.drop_column('platform_users', 'readable_id')
    # ### end Alembic commands ###
