"""add readable_id to tenant

Revision ID: 454e6b31d7cb
Revises: a51b6a72cb4a
Create Date: 2026-03-04 07:38:07.816785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454e6b31d7cb'
down_revision: Union[str, Sequence[str], None] = 'a51b6a72cb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('readable_id', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['readable_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'readable_id')
    # ### end Alembic commands ###
