"""Add hotel images

Revision ID: 6fcf7f8815ca
Revises: 703b54b67d53
Create Date: 2026-02-26 07:39:37.120464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcf7f8815ca'
down_revision: Union[str, Sequence[str], None] = '703b54b67d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('image_url_1', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('image_url_2', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('image_url_3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'image_url_3')
    op.drop_column('tenants', 'image_url_2')
    op.drop_column('tenants', 'image_url_1')
    # ### end Alembic commands ###
