"""add_price_to_plans

Revision ID: a344ef4e062a
Revises: ca92b327e169
Create Date: 2026-02-19 10:09:13.406688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a344ef4e062a"
down_revision: Union[str, Sequence[str], None] = "ca92b327e169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans", sa.Column("price", sa.Float(), nullable=False, server_default="0.0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "price")
    # ### end Alembic commands ###
