"""Add description and color to platform roles

Revision ID: a51b6a72cb4a
Revises: 0cd91be3c5f3
Create Date: 2026-03-04 07:17:10.365974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51b6a72cb4a'
down_revision: Union[str, Sequence[str], None] = '0cd91be3c5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('platform_roles', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_roles', 'color')
    op.drop_column('platform_roles', 'description')
    # ### end Alembic commands ###
