"""apply_kiosk_schema

Revision ID: a56ed45b6a79
Revises: 6fcf7f8815ca
Create Date: 2026-02-28 07:21:04.794765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a56ed45b6a79'
down_revision: Union[str, Sequence[str], None] = '6fcf7f8815ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('check_in_time', sa.String(length=10), nullable=False),
    sa.Column('check_out_time', sa.String(length=10), nullable=False),
    sa.Column('default_lang', sa.String(length=10), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=190), nullable=True),
    sa.Column('payment_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('support_messages')
    op.alter_column('plans', 'period_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('subscriptions', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.alter_column('subscriptions', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('support_tickets_tenant_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenant_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('tenant_roles_tenant_id_fkey'), 'tenant_roles', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenant_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('tenant_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('tenant_users_tenant_id_fkey'), 'tenant_users', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('tenants', sa.Column('slug', sa.String(length=100), nullable=False))
    op.alter_column('tenants', 'image_url_1',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tenants', 'image_url_2',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tenants', 'image_url_3',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint(None, 'tenants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tenants', 'image_url_3',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tenants', 'image_url_2',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tenants', 'image_url_1',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tenants', 'slug')
    op.drop_constraint(None, 'tenant_users', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_users_tenant_id_fkey'), 'tenant_users', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tenant_users', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tenant_users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'tenant_roles', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_roles_tenant_id_fkey'), 'tenant_roles', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tenant_roles', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_tenant_id_fkey'), 'support_tickets', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('support_tickets', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('subscriptions', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('subscriptions', 'plan_id')
    op.alter_column('plans', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('plans', 'period_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('support_messages_ticket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('support_messages_pkey'))
    )
    op.drop_table('bookings')
    op.drop_table('tenant_configs')
    op.drop_table('room_types')
    # ### end Alembic commands ###
